version: "3.8"
services:
  localstack:
    image: localstack/localstack
    network_mode: bridge
    container_name: localstack
    ports:
      - "8566:4566" # port of to where localstack can be addressed to
      - "9000:9000"
    environment:
      - DEBUG=${DEBUG-}
      - SERVICES=sqs,dynamodb # a list of desired services you want to use.
      - DEFAULT_REGION=eu-west-2 # This is the region where your localstack mocks to be running
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=9000
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
